# Utiliza una imagen base oficial de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo en /app
WORKDIR /app

# Copiar el resto del código fuente al contenedor
COPY . .

# Instalar pip y las dependencias necesarias
RUN pip install --no-cache-dir \
    pydantic==1.10.7 \
    langchain==0.0.208 \
    openai==0.27.4 \
    requests python-dotenv

# Ejecutar el script cuando el contenedor se inicie
CMD ["python", "model.py"]
